# Generated by Django 4.0 on 2023-06-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
