# Generated by Django 4.0 on 2023-06-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='purchased_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
